sudo: required
language: cpp
dist: trusty

notifications:
  email: false

services:
  docker

before_install:
  #  - docker pull bartekt/can_dev_base_image
  - export ci_env=`bash <(curl -s https://codecov.io/env)`
  # Install newer cmake because it includes the GoogleTest module
  - wget https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.sh
  - sudo bash cmake-3.9.6-Linux-x86_64.sh --prefix=/usr --exclude-subdir

script:
  - export CC=gcc-53 CXX=g++-53 CMAKE_BUILD_TYPE=Release
  - ./.travis.sh
  - export CC=gcc-53 CXX=g++-53 CMAKE_BUILD_TYPE=Debug 
  - ./.travis.sh
  - export CC=clang-3.5 CXX=clang++-3.5 CMAKE_BUILD_TYPE=Release
  - ./.travis.sh
  - export CC=clang-3.5 CXX=clang++-3.5 CMAKE_BUILD_TYPE=Debug
  - ./.travis.sh
  - export CC=gcc-6 CXX=g++-6 CMAKE_BUILD_TYPE=Debug WITH_COVERAGE=ON
  - ./.travis.sh
    
